name: CI Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Check Workflow
        run: |
          echo "GitHub Actions Started"
          echo "Repository Checkout Complete"
